### ISSUE TITLE
Impose quota on disk usage

### ISSUE THREAD

**Issue by lthibault** [arve0/docker-timemachine#1]
It would be nice if some sort of environment variable could limit the amount of disk space that time machine could use.  Does such a feature already exist?

**Comment by arve0** [comment]
There is a setting for that in afp.conf called 'vol size limit'. See http://netatalk.sourceforge.net/3.0/htmldocs/afp.conf.5.html for more info.

**Comment by lthibault** [comment]
Wonderful, thank you!
